from collections.abc import Callable, Sequence
from typing import Protocol, TypeVar

from .models import AdminRole, Appeal, ApprovalRequest, AuditEvent, ReviewRecord, RuleVersion

T = TypeVar("T")


class RulePort(Protocol):
    def atomic(self, tenant_id: str, idempotency_key: str, operation: Callable[[], T]) -> T: ...
    def next_rule_sequence(self, tenant_id: str) -> int: ...
    def save_rule_version(self, version: RuleVersion) -> None: ...
    def current_rule_version(self, tenant_id: str) -> RuleVersion | None: ...
    def get_rule_version(self, tenant_id: str, version_id: str) -> RuleVersion: ...


class ReviewPort(Protocol):
    def save_review(self, review: ReviewRecord) -> None: ...
    def get_review(self, tenant_id: str, review_id: str) -> ReviewRecord: ...
    def list_reviews(self, tenant_id: str, *, status: str | None = None) -> Sequence[ReviewRecord]: ...
    def save_appeal(self, appeal: Appeal) -> None: ...
    def get_appeal(self, tenant_id: str, appeal_id: str) -> Appeal: ...
    def save_approval(self, approval: ApprovalRequest) -> None: ...
    def get_approval(self, tenant_id: str, approval_id: str) -> ApprovalRequest: ...
    def save_role(self, role: AdminRole) -> None: ...
    def get_role(self, tenant_id: str, role_id: str) -> AdminRole: ...


class AuditPort(Protocol):
    def append_audit(self, event: AuditEvent) -> None: ...
    def query_audit(
        self,
        tenant_id: str,
        *,
        actor_id: str | None = None,
        object_id: str | None = None,
        request_id: str | None = None,
    ) -> Sequence[AuditEvent]: ...
