from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path


class ObjectNotFound(FileNotFoundError):
    """The scoped object is not present in object storage."""


@dataclass(frozen=True, slots=True)
class StoredObject:
    content: bytes
    size_bytes: int
    sha256: str


class LocalStoryboardObjectStorage:
    """Filesystem implementation of the M05 object-storage port.

    Keys are generated by the runtime, while scope is supplied separately on every
    operation.  The resulting path is always rooted below ``root``; identifiers
    are constrained rather than joined from client-controlled path fragments.
    This deliberately small port can be replaced by S3/OSS without changing the
    HTTP layer.
    """

    _SAFE_SEGMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
    _SAFE_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,1023}$")

    def __init__(self, root: str | Path) -> None:
        candidate = Path(root).expanduser()
        if not candidate.is_absolute():
            raise ValueError("STORYBOARD_STORAGE_ROOT_MUST_BE_ABSOLUTE")
        self._root = candidate.resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def put_bytes(self, *, tenant_id: str, workspace_id: str, project_id: str, key: str, content: bytes) -> StoredObject:
        return self.put_chunks(
            tenant_id=tenant_id,
            workspace_id=workspace_id,
            project_id=project_id,
            key=key,
            chunks=(content,),
        )

    def put_chunks(
        self,
        *,
        tenant_id: str,
        workspace_id: str,
        project_id: str,
        key: str,
        chunks: Iterable[bytes],
    ) -> StoredObject:
        target = self._path(tenant_id, workspace_id, project_id, key)
        target.parent.mkdir(parents=True, exist_ok=True)
        digest = hashlib.sha256()
        size = 0
        descriptor, temporary_name = tempfile.mkstemp(prefix=".upload-", dir=target.parent)
        try:
            with os.fdopen(descriptor, "wb") as stream:
                for chunk in chunks:
                    stream.write(chunk)
                    digest.update(chunk)
                    size += len(chunk)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary_name, target)
        except BaseException:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
            raise
        return StoredObject(content=b"", size_bytes=size, sha256=digest.hexdigest())

    def get_bytes(self, *, tenant_id: str, workspace_id: str, project_id: str, key: str) -> StoredObject:
        path = self._path(tenant_id, workspace_id, project_id, key)
        try:
            content = path.read_bytes()
        except FileNotFoundError as error:
            raise ObjectNotFound(key) from error
        return StoredObject(content=content, size_bytes=len(content), sha256=hashlib.sha256(content).hexdigest())

    def put_json(self, *, tenant_id: str, workspace_id: str, project_id: str, key: str, value: dict[str, str]) -> None:
        self.put_bytes(
            tenant_id=tenant_id,
            workspace_id=workspace_id,
            project_id=project_id,
            key=key,
            content=json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8"),
        )

    def get_json(self, *, tenant_id: str, workspace_id: str, project_id: str, key: str) -> dict[str, str]:
        raw = self.get_bytes(tenant_id=tenant_id, workspace_id=workspace_id, project_id=project_id, key=key).content
        value = json.loads(raw)
        if not isinstance(value, dict) or not all(isinstance(item, str) for item in value.values()):
            raise ValueError("INVALID_OBJECT_METADATA")
        return value

    def _path(self, tenant_id: str, workspace_id: str, project_id: str, key: str) -> Path:
        segments = (tenant_id, workspace_id, project_id)
        if any(not self._SAFE_SEGMENT.fullmatch(item) for item in segments) or not self._SAFE_KEY.fullmatch(key):
            raise ValueError("INVALID_OBJECT_STORAGE_PATH")
        candidate = (self._root / tenant_id / workspace_id / project_id / key).resolve()
        try:
            candidate.relative_to(self._root)
        except ValueError as error:
            raise ValueError("INVALID_OBJECT_STORAGE_PATH") from error
        return candidate
