import { Clapperboard, Film, ImagePlus, LoaderCircle, RefreshCw, RotateCcw, Send, Sparkles, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";

import { GenerationCenterApiError, generationCenterApi, type GenerationCenterApi } from "./api";
import { canCancelTask, canRetryTask, isProcessingTask, taskStatusText, type GenerationCandidateSet, type GenerationModelAvailability, type GenerationModelUsageReport, type GenerationSubmission, type GenerationTask, type GenerationTaskDetail, type GenerationTaskFilters, type GenerationWorkbenchView, type GenerationWorkspaceScope } from "./contracts";

const copy: Record<GenerationWorkbenchView, { title: string; eyebrow: string; description: string; icon: typeof Sparkles; capability: string; media: "image" | "video"; acceptsInput?: boolean; submit?: boolean }> = {
  center: { title: "生成中心", eyebrow: "GENERATION CONTROL ROOM", description: "跨镜头查看生成执行、模型路由与产物版本。", icon: Sparkles, capability: "generation", media: "image", submit: true },
  image: { title: "图片生成工作台", eyebrow: "STILL FRAME LAB", description: "围绕角色、场景与分镜首帧组织图片生成任务。", icon: ImagePlus, capability: "image_generation", media: "image", submit: true },
  "image-to-video": { title: "图生视频", eyebrow: "FRAME TO MOTION", description: "从故事板首帧、角色图或场景图追踪镜头视频任务。", icon: Film, capability: "image_to_video", media: "video", acceptsInput: true, submit: true },
  "text-to-video": { title: "文生视频", eyebrow: "SCRIPT TO MOTION", description: "按分镜文本、运镜与情绪观察视频候选生成。", icon: Clapperboard, capability: "text_to_video", media: "video", submit: true },
  video: { title: "视频生成工作台", eyebrow: "MOTION FINISHING", description: "集中查看视频生成、延展、去闪与高清处理任务。", icon: Film, capability: "video_generation", media: "video", acceptsInput: true, submit: true },
  tasks: { title: "任务中心", eyebrow: "PRODUCTION QUEUE", description: "查看当前项目的排队、运行、失败与取消结果。", icon: LoaderCircle, capability: "generation", media: "video" },
  "first-last-video": { title: "首尾帧视频", eyebrow: "KEYFRAME MOTION", description: "用首帧与尾帧约束镜头运动和收束画面。", icon: Film, capability: "first_last_video", media: "video", acceptsInput: true, submit: true },
  "image-edit": { title: "图片编辑", eyebrow: "IMAGE EDIT LAB", description: "提交受控图片编辑任务并保留输入资产关联。", icon: ImagePlus, capability: "image_edit", media: "image", acceptsInput: true, submit: true },
  inpaint: { title: "局部重绘", eyebrow: "INPAINT CONTROL", description: "以遮罩与原图资产为输入生成局部修复版本。", icon: ImagePlus, capability: "inpaint", media: "image", acceptsInput: true, submit: true },
  "reference-fusion": { title: "多图参考融合", eyebrow: "REFERENCE FUSION", description: "将多张角色或场景参考资产提交给模型融合。", icon: ImagePlus, capability: "reference_fusion", media: "image", acceptsInput: true, submit: true },
  "image-upscale": { title: "高清放大", eyebrow: "IMAGE UPSCALE", description: "提交已有图片资产的超分与细节修复。", icon: ImagePlus, capability: "image_upscale", media: "image", acceptsInput: true, submit: true },
  "model-center": { title: "模型中心", eyebrow: "MODEL CONTROL", description: "查看当前工作区生成任务实际解析到的 Provider 与模型。", icon: Sparkles, capability: "generation", media: "image" },
  "model-detail": { title: "模型详情", eyebrow: "MODEL TRACE", description: "从真实任务记录查看模型路由、版本与产物关联。", icon: Sparkles, capability: "generation", media: "image" },
  "model-market": { title: "模型市场", eyebrow: "MODEL CATALOG", description: "展示当前部署已接入的模型能力；未配置的模型不会伪造可用。", icon: Sparkles, capability: "generation", media: "image" },
  "model-report": { title: "模型使用报告", eyebrow: "MODEL USAGE", description: "按真实任务记录查看模型调用状态与产物追踪。", icon: Sparkles, capability: "generation", media: "image" },
  "video-candidates": { title: "视频候选对比", eyebrow: "CANDIDATE REVIEW", description: "从服务端确认的生成产物中并排比对候选版本。", icon: Film, capability: "video_candidates", media: "video", acceptsInput: true, submit: true },
  "video-extend": { title: "视频延展", eyebrow: "MOTION EXTEND", description: "以已有视频资产为输入延长镜头和环境运动。", icon: Film, capability: "video_extend", media: "video", acceptsInput: true, submit: true },
  "video-retry": { title: "视频重试策略", eyebrow: "RECOVERY CONTROL", description: "从失败任务复制输入后以新请求重新提交；不会覆盖旧任务。", icon: Film, capability: "video_retry", media: "video", acceptsInput: true, submit: true },
  "video-stabilize": { title: "视频去闪稳定", eyebrow: "FRAME STABILIZE", description: "对服务端已确认的视频资产提交去闪和稳定化任务。", icon: Film, capability: "video_stabilize", media: "video", acceptsInput: true, submit: true },
  "video-upscale": { title: "视频高清修复", eyebrow: "VIDEO RESTORATION", description: "对已有视频资产提交超分、补帧和修复任务。", icon: Film, capability: "video_upscale", media: "video", acceptsInput: true, submit: true },
};

function errorText(error: unknown): string {
  if (!(error instanceof GenerationCenterApiError)) return "网络暂不可用，请稍后重新读取服务端状态。";
  if (error.status === 403) return "服务端拒绝了当前工作区或项目的数据访问；不会显示任何任务详情。";
  if (error.status === 409) return "任务版本已变化。已保留当前界面，并请重新读取服务端最终状态。";
  if (error.status === 503) return "生成服务当前不可用，未提交或伪造任何任务结果。";
  if (error.code === "GENERATION_PROVIDER_CANCELLATION_UNAVAILABLE") return "该任务正在供应商侧运行，当前部署尚不能确认取消；服务端状态未被改写。";
  return `${error.message}${error.requestId ? `（请求 ${error.requestId}）` : ""}`;
}

function statusClass(status: GenerationTask["status"]): string {
  if (status === "succeeded") return "border-emerald-400/30 bg-emerald-400/10 text-emerald-200";
  if (["failed", "timeout", "cancelled"].includes(status)) return "border-rose-400/30 bg-rose-400/10 text-rose-200";
  return "border-amber-300/30 bg-amber-300/10 text-amber-100";
}

function formatTime(value: string | null): string { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }

function TaskRow({ task, selected, onSelect, onCancel, onRetry, busy }: { readonly task: GenerationTask; readonly selected: boolean; readonly onSelect: () => void; readonly onCancel: () => void; readonly onRetry: () => void; readonly busy: boolean }) {
  return <article className={`group grid gap-3 border-b border-white/10 px-5 py-4 transition hover:bg-white/[0.045] md:grid-cols-[minmax(180px,1.25fr)_120px_130px_120px_76px] ${selected ? "bg-cyan-300/[0.08]" : ""}`}>
    <button type="button" onClick={onSelect} className="min-w-0 text-left"><strong className="block truncate font-mono text-xs text-stone-100">{task.task_id}</strong><span className="mt-1 block truncate text-xs text-stone-400">{task.request.prompt}</span></button>
    <button type="button" onClick={onSelect} className="text-left text-xs text-stone-300">{task.request.capability}</button>
    <button type="button" onClick={onSelect} className="text-left"><span className={`inline-flex rounded-full border px-2 py-1 text-[11px] font-medium ${statusClass(task.status)}`}>{taskStatusText[task.status]}</span><span className="mt-1 block text-[11px] text-stone-500">v{task.version} · 第 {task.attempt + 1} 次</span></button>
    <button type="button" onClick={onSelect} className="text-left text-xs text-stone-400">{formatTime(task.updated_at)}</button>
    <span className="flex items-center gap-1">{canRetryTask(task.status) ? <button type="button" onClick={onRetry} aria-label={`重试任务 ${task.task_id}`} disabled={busy} className="grid place-items-center rounded p-2 text-stone-400 hover:bg-cyan-400/15 hover:text-cyan-100 disabled:opacity-50"><RotateCcw size={16} /></button> : null}{canCancelTask(task.status) ? <button type="button" onClick={onCancel} aria-label={`取消任务 ${task.task_id}`} disabled={busy} className="grid place-items-center rounded p-2 text-stone-400 hover:bg-rose-400/15 hover:text-rose-200 disabled:opacity-50"><XCircle size={17} /></button> : null}</span>
  </article>;
}

function SubmissionConsole({ config, scope, api, onSubmitted }: { readonly config: typeof copy[GenerationWorkbenchView]; readonly scope: GenerationWorkspaceScope; readonly api: GenerationCenterApi; readonly onSubmitted: (task: GenerationTask) => Promise<void> }) {
  const [prompt, setPrompt] = useState(""); const [assets, setAssets] = useState(""); const [providerId, setProviderId] = useState(""); const [modelId, setModelId] = useState(""); const [parameters, setParameters] = useState("{}"); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const idempotency = useRef<string | undefined>(undefined);
  if (!config.submit) return null;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); if (!prompt.trim()) { setError("请先填写生成提示词或修复说明。"); return; } if (config.acceptsInput && !assets.trim()) { setError("此能力必须提供至少一个已入库的输入资产 ID。"); return; } let parsed: Record<string, unknown>; try { const candidate: unknown = JSON.parse(parameters); if (!candidate || Array.isArray(candidate) || typeof candidate !== "object") throw new Error(); parsed = candidate as Record<string, unknown>; } catch { setError("高级参数必须是 JSON 对象。"); return; } if ((providerId.trim() && !modelId.trim()) || (!providerId.trim() && modelId.trim())) { setError("Provider 与模型需要同时填写，或都留空由服务端路由。"); return; } setSubmitting(true); try { const idempotencyKey = idempotency.current ?? `xj:${scope.projectId}:submit:${globalThis.crypto?.randomUUID?.() ?? Date.now()}`; idempotency.current = idempotencyKey; const task = await api.submit(scope.projectId, { media_type: config.media, capability: config.capability, prompt: prompt.trim(), parameters: parsed, input_asset_ids: assets.split(",").map((value) => value.trim()).filter(Boolean), ...(providerId.trim() ? { requested_provider_id: providerId.trim(), requested_model_id: modelId.trim() } : {}) } satisfies GenerationSubmission, idempotencyKey); idempotency.current = undefined; await onSubmitted(task); setPrompt(""); setAssets(""); setParameters("{}"); } catch (reason) { setError(errorText(reason)); } finally { setSubmitting(false); } };
  return <section className="border border-cyan-200/20 bg-[linear-gradient(110deg,rgba(8,47,73,.48),rgba(23,20,17,.82))] p-5 shadow-[inset_3px_0_0_rgb(103_232_249)]" aria-label="提交生成任务"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[11px] tracking-[.16em] text-cyan-200">LIVE SUBMISSION</p><h2 className="mt-1 font-semibold text-cyan-50">提交 {config.title} 任务</h2><p className="mt-1 text-sm text-stone-400">任务由服务端分配工作区和项目范围；按钮只调用真实提交接口。</p></div><Send className="text-cyan-200" size={20} /></div><form onSubmit={(event) => void submit(event)} className="mt-4 grid gap-3 lg:grid-cols-2"><label className="lg:col-span-2 text-xs text-stone-400">提示词 / 修复说明<textarea value={prompt} onChange={(event) => { setPrompt(event.target.value); idempotency.current = undefined; }} required rows={3} className="mt-1 block w-full border border-white/10 bg-black/30 px-3 py-2 text-sm text-stone-100 outline-none focus:border-cyan-200/60" /></label>{config.acceptsInput ? <label className="text-xs text-stone-400">输入资产 ID（逗号分隔）<input value={assets} onChange={(event) => { setAssets(event.target.value); idempotency.current = undefined; }} required className="mt-1 block w-full border border-white/10 bg-black/30 px-3 py-2 text-sm text-stone-100 outline-none focus:border-cyan-200/60" /></label> : null}<label className="text-xs text-stone-400">Provider（可选）<input value={providerId} onChange={(event) => { setProviderId(event.target.value); idempotency.current = undefined; }} className="mt-1 block w-full border border-white/10 bg-black/30 px-3 py-2 text-sm text-stone-100 outline-none focus:border-cyan-200/60" /></label><label className="text-xs text-stone-400">模型（可选）<input value={modelId} onChange={(event) => { setModelId(event.target.value); idempotency.current = undefined; }} className="mt-1 block w-full border border-white/10 bg-black/30 px-3 py-2 text-sm text-stone-100 outline-none focus:border-cyan-200/60" /></label><label className="lg:col-span-2 text-xs text-stone-400">高级参数（JSON 对象）<input value={parameters} onChange={(event) => { setParameters(event.target.value); idempotency.current = undefined; }} className="mt-1 block w-full border border-white/10 bg-black/30 px-3 py-2 font-mono text-xs text-stone-100 outline-none focus:border-cyan-200/60" /></label>{error ? <p role="alert" className="lg:col-span-2 border border-rose-400/30 bg-rose-950/25 p-3 text-sm text-rose-100">{error}</p> : null}<div className="lg:col-span-2 flex items-center justify-between gap-3"><span className="text-xs text-stone-500">{scope.projectName ?? scope.projectId} · {config.capability}</span><button type="submit" disabled={submitting} className="inline-flex items-center gap-2 bg-cyan-200 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"><Send size={15} />{submitting ? "正在交给服务端…" : "提交真实任务"}</button></div></form></section>;
}

function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes < 0) return "大小未知";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 ** 2).toFixed(1)} MB`;
}

function formatMoney(minor: number, currency: string): string {
  return new Intl.NumberFormat("zh-CN", { style: "currency", currency, minimumFractionDigits: 2 }).format(minor / 100);
}

function ModelStatus({ model }: { readonly model: GenerationModelAvailability | null }) {
  if (!model) return null;
  return <section className="border border-cyan-200/20 bg-cyan-200/[0.04] p-5"><p className="font-mono text-[11px] tracking-[.16em] text-cyan-200">DEPLOYED MODEL ROUTE</p>{model.provider_id && model.model_id ? <><h2 className="mt-2 text-lg font-semibold text-cyan-50">{model.provider_id} / {model.model_id}</h2><p className="mt-2 text-sm text-stone-400">提交：{model.submission_available ? "可用" : "未部署"} · 回调与产物确认：{model.callback_available ? "可用" : "未部署"}</p>{model.billing_currency && model.estimated_cost_minor !== null ? <p className="mt-1 text-xs text-stone-500">单次预冻结 {formatMoney(model.estimated_cost_minor, model.billing_currency)} · 价格版本 {model.pricing_version ?? "未配置"}</p> : <p className="mt-1 text-xs text-amber-100">尚未部署权威计费策略，禁止提交付费任务。</p>}</> : <p className="mt-2 text-sm text-amber-100">当前没有已部署的 M06 Provider；模型市场不会虚构可选模型。</p>}</section>;
}

function ModelCatalogPanel({ model }: { readonly model: GenerationModelAvailability | null }) {
  if (!model) return null;
  const models = model.models ?? [];
  return <section className="border border-violet-200/20 bg-violet-200/[0.04] p-5"><p className="font-mono text-[11px] tracking-[.16em] text-violet-200">DEPLOYED MODEL CATALOG</p><h2 className="mt-2 text-lg font-semibold text-violet-50">模型能力目录</h2>{models.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{models.map((item) => <article key={`${item.provider_id}:${item.model_id}`} className="border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><strong className="text-stone-100">{item.display_name}</strong><p className="mt-1 font-mono text-xs text-stone-400">{item.provider_id} / {item.model_id}</p></div><span className={`border px-2 py-1 text-[10px] ${item.active ? "border-emerald-300/30 text-emerald-200" : "border-stone-500/30 text-stone-500"}`}>{item.active ? "已上线" : "已下线"}</span></div><p className="mt-3 text-xs text-stone-400">版本 {item.version} · 区域 {item.region} · {item.media_types.join(" / ")}</p><p className="mt-2 break-words text-xs leading-5 text-stone-500">{item.capabilities.join(" · ")}</p></article>)}</div> : <p className="mt-3 text-sm text-amber-100">部署端尚未配置模型目录，因此服务端会拒绝生成提交。</p>}</section>;
}

function ModelUsagePanel({ usage }: { readonly usage: readonly GenerationModelUsageReport[] }) {
  return <section className="border border-violet-200/20 bg-violet-200/[0.04] p-5"><p className="font-mono text-[11px] tracking-[.16em] text-violet-200">RECORDED MODEL USAGE</p><h2 className="mt-2 text-lg font-semibold text-violet-50">模型使用报告</h2>{usage.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{usage.map((item) => <article key={`${item.provider_id}:${item.model_id}`} className="border border-white/10 bg-black/20 p-4"><p className="font-mono text-xs text-stone-200">{item.provider_id ?? "未解析 Provider"} / {item.model_id ?? "未解析模型"}</p><p className="mt-2 text-sm text-stone-300">任务 {item.task_count} · 成功 {item.succeeded_count} · 处理中 {item.processing_count} · 失败/取消 {item.failed_count}</p>{item.costs.length ? <div className="mt-2 space-y-1 text-xs text-stone-400">{item.costs.map((cost) => <p key={cost.currency}>{cost.currency} · 预估 {formatMoney(cost.estimated_minor, cost.currency)} · 实际 {formatMoney(cost.actual_minor, cost.currency)}</p>)}</div> : <p className="mt-2 text-xs text-stone-500">Provider 尚未回传计量，不能显示虚构费用。</p>}</article>)}</div> : <p className="mt-3 text-sm text-stone-500">当前项目还没有服务端保存的模型调用记录。</p>}</section>;
}

function artifactUrl(scope: GenerationWorkspaceScope, assetId: string): string {
  return `/api/v1/generation-assets/${encodeURIComponent(assetId)}/content?projectId=${encodeURIComponent(scope.projectId)}`;
}

function CandidateComparison({ scope, candidates, total, selecting, onSelectCandidate }: { readonly scope: GenerationWorkspaceScope; readonly candidates: readonly GenerationCandidateSet[]; readonly total: number; readonly selecting: boolean; readonly onSelectCandidate: (taskId: string, assetId: string, expectedVersion: number) => void }) {
  return <section className="border border-cyan-200/20 bg-cyan-200/[0.035] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[11px] tracking-[.16em] text-cyan-200">SERVER-CONFIRMED CANDIDATES</p><h2 className="mt-1 text-lg font-semibold text-cyan-50">视频候选对比</h2><p className="mt-1 text-sm text-stone-400">仅显示已成功入库的真实产物；可并排查看模型、版本、成本和输出差异。</p></div><span className="text-sm text-stone-500">共 {total} 组候选</span></div>{candidates.length ? <div className="mt-4 grid gap-4 2xl:grid-cols-2">{candidates.map((candidate) => <article key={candidate.task.task_id} className="border border-white/10 bg-black/25 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-stone-200">{candidate.task.task_id}</p><p className="mt-1 text-xs text-stone-500">{candidate.task.resolved_provider_id ?? "待解析"} / {candidate.task.resolved_model_id ?? "待解析"} · {candidate.task.request.capability}</p></div><span className="text-xs text-stone-500">第 {candidate.task.attempt + 1} 次</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{candidate.assets.map((asset) => <div key={asset.asset_id} className="border border-white/10 bg-stone-950/60 p-2"><video controls preload="metadata" className="aspect-video w-full bg-black object-contain" src={artifactUrl(scope, asset.asset_id)}><track kind="captions" /></video><p className="mt-2 break-all font-mono text-[10px] text-stone-300">{asset.asset_id}</p><p className="mt-1 text-[10px] text-stone-500">{formatBytes(asset.size_bytes)} · {asset.content_sha256.slice(0, 16)}…</p><button type="button" disabled={selecting || candidate.selectedCandidate?.selected_asset_id === asset.asset_id} onClick={() => onSelectCandidate(candidate.task.task_id, asset.asset_id, candidate.selectedCandidate?.version ?? 0)} className="mt-2 border border-cyan-200/30 px-2 py-1 text-[11px] text-cyan-100 disabled:opacity-50">{candidate.selectedCandidate?.selected_asset_id === asset.asset_id ? "已保留此版本" : "保留此版本"}</button></div>)}</div>{candidate.assets.length < 2 ? <p className="mt-3 text-xs text-stone-500">此任务目前只有一个已确认输出；可从其他任务继续比较模型结果。</p> : null}</article>)}</div> : <p className="mt-4 text-sm text-stone-500">还没有可比较的已完成视频产物。</p>}</section>;
}

function DetailPanel({ detail, onClose, onSelectCandidate, selecting }: { readonly detail: GenerationTaskDetail | null; readonly onClose: () => void; readonly onSelectCandidate: (assetId: string) => void; readonly selecting: boolean }) {
  if (!detail) return <aside className="border border-white/10 bg-stone-950/50 p-5 text-sm text-stone-500">选择任务以读取服务端详情、产物 ID、校验摘要与更新时间。</aside>;
  const task = detail.task;
  return <aside className="border border-white/10 bg-stone-950/80 p-5">
    <div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[11px] text-cyan-200">TASK DETAIL</p><h2 className="mt-1 font-mono text-sm text-stone-100">{task.task_id}</h2></div><button type="button" onClick={onClose} className="text-sm text-stone-400 hover:text-stone-100">关闭</button></div>
    <dl className="mt-5 grid gap-4 text-sm">
      <div><dt className="text-xs text-stone-500">模型路由</dt><dd className="mt-1 font-mono text-xs text-stone-200">{task.resolved_provider_id ?? "待解析"} / {task.resolved_model_id ?? "待解析"}</dd></div>
      <div><dt className="text-xs text-stone-500">输入摘要</dt><dd className="mt-1 leading-6 text-stone-300">{task.request.prompt}</dd></div>
      <div><dt className="text-xs text-stone-500">状态与时限</dt><dd className="mt-1 text-stone-300">{taskStatusText[task.status]} · 截止 {formatTime(task.timeout_at)}{detail.progress.queue_position ? ` · 队列第 ${detail.progress.queue_position} 位` : ""}</dd>{detail.progress.latest ? <div className="mt-2"><div className="h-1.5 overflow-hidden bg-white/10"><span className="block h-full bg-cyan-300" style={{ width: `${detail.progress.latest.percent}%` }} /></div><p className="mt-1 text-xs text-cyan-100">{detail.progress.latest.percent}% · {detail.progress.latest.message}{detail.progress.latest.eta_seconds !== null ? ` · 预计 ${detail.progress.latest.eta_seconds} 秒` : ""}</p></div> : null}</div>
      <div><dt className="text-xs text-stone-500">算力冻结与结算</dt><dd className="mt-1 text-stone-300">{detail.billing ? `${detail.billing.status} · 冻结 ${formatMoney(detail.billing.estimated_minor, detail.billing.currency)} · 实耗 ${formatMoney(detail.billing.actual_minor, detail.billing.currency)} · 退回 ${formatMoney(detail.billing.released_minor, detail.billing.currency)} · ${detail.billing.pricing_version}` : "未找到该任务的账务冻结记录。"}</dd></div>
      <div><dt className="text-xs text-stone-500">实际计量</dt><dd className="mt-1 text-stone-300">{detail.costEvidence.length ? detail.costEvidence.map((cost) => <p key={cost.evidence_id}>{cost.currency} · 预估 {formatMoney(cost.estimated_minor, cost.currency)} · 实际 {formatMoney(cost.actual_minor, cost.currency)} · {cost.pricing_version}</p>) : "Provider 尚未返回计量，不显示虚构成本。"}</dd></div>
      {task.failure ? <div className="border border-rose-400/20 bg-rose-400/5 p-3"><dt className="text-xs text-rose-200">失败原因 · {task.failure.code}</dt><dd className="mt-1 text-sm text-rose-100">{task.failure.message}</dd></div> : null}
      <div><dt className="text-xs text-stone-500">已确认产物</dt><dd className="mt-2 space-y-2">{detail.generatedAssets.length ? detail.generatedAssets.map((asset) => <div key={asset.asset_id} className="border border-white/10 bg-white/[0.03] p-2"><p className="font-mono text-[11px] text-stone-200">{asset.asset_id} · {asset.media_type} · {formatBytes(asset.size_bytes)}</p><p className="mt-1 break-all font-mono text-[10px] text-stone-500">SHA-256 {asset.content_sha256}</p><p className="mt-1 text-[11px] text-stone-400">{Object.keys(asset.metadata).length ? JSON.stringify(asset.metadata) : "无附加元数据"}</p><button type="button" disabled={selecting || detail.selectedCandidate?.selected_asset_id === asset.asset_id} onClick={() => onSelectCandidate(asset.asset_id)} className="mt-2 border border-cyan-200/30 px-2 py-1 text-[11px] text-cyan-100 disabled:opacity-50">{detail.selectedCandidate?.selected_asset_id === asset.asset_id ? "已选为候选" : "选为候选"}</button></div>) : <span className="text-stone-500">尚无服务端确认的产物</span>}</dd></div>
    </dl>
  </aside>;
}

export interface GenerationWorkbenchProps { readonly scope: GenerationWorkspaceScope; readonly view?: GenerationWorkbenchView; readonly api?: GenerationCenterApi }

export function GenerationWorkbench({ scope, view = "center", api = generationCenterApi }: GenerationWorkbenchProps) {
  const config = copy[view]; const Icon = config.icon; const [tasks, setTasks] = useState<readonly GenerationTask[]>([]); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(0); const [filters, setFilters] = useState<GenerationTaskFilters>({}); const [model, setModel] = useState<GenerationModelAvailability | null>(null); const [usage, setUsage] = useState<readonly GenerationModelUsageReport[]>([]); const [candidates, setCandidates] = useState<readonly GenerationCandidateSet[]>([]); const [candidateTotal, setCandidateTotal] = useState(0); const [selected, setSelected] = useState<GenerationTaskDetail | null>(null); const [state, setState] = useState<"loading" | "ready" | "forbidden" | "error">("loading"); const [message, setMessage] = useState(""); const [busyId, setBusyId] = useState<string>(); const controller = useRef<AbortController | null>(null);
  const load = useCallback(async () => { controller.current?.abort(); const signalController = new AbortController(); controller.current = signalController; setState("loading"); try { const [page, availability, recordedUsage, candidatePage] = await Promise.all([api.list(scope.projectId, offset, 50, signalController.signal, filters), api.models(scope.projectId, signalController.signal), view === "model-report" ? api.usage(scope.projectId, signalController.signal) : Promise.resolve([]), view === "video-candidates" ? api.candidates(scope.projectId, { mediaType: "video", offset: 0, limit: 20, signal: signalController.signal }) : Promise.resolve(null)]); setTasks(page.tasks); setTotal(page.total); setModel(availability); setUsage(recordedUsage); setCandidates(candidatePage?.candidates ?? []); setCandidateTotal(candidatePage?.total ?? 0); setSelected((current) => current ? { ...current, task: page.tasks.find((task) => task.task_id === current.task.task_id) ?? current.task } : null); setState("ready"); } catch (error) { if (signalController.signal.aborted) return; setState(error instanceof GenerationCenterApiError && error.status === 403 ? "forbidden" : "error"); setMessage(errorText(error)); } }, [api, filters, offset, scope.projectId, view]);
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => { window.clearTimeout(timer); controller.current?.abort(); };
  }, [load]);
  const processing = useMemo(() => tasks.filter((task) => isProcessingTask(task.status)).length, [tasks]);
  const readDetail = async (task: GenerationTask) => { try { setSelected(await api.detail(scope.projectId, task.task_id)); } catch (error) { setMessage(errorText(error)); } };
  const cancel = async (task: GenerationTask) => { setBusyId(task.task_id); setMessage(""); try { await api.cancel(scope.projectId, task, `xj:${scope.projectId}:cancel:${task.task_id}:${task.version}`); await load(); await readDetail(task); } catch (error) { setMessage(errorText(error)); if (error instanceof GenerationCenterApiError && error.status === 409) await load(); } finally { setBusyId(undefined); } };
  const retry = async (task: GenerationTask) => { setBusyId(task.task_id); setMessage(""); try { const retried = await api.retry(scope.projectId, task, `xj:${scope.projectId}:retry:${task.task_id}:${task.version}`); setMessage(`已从 ${task.task_id} 创建新的恢复任务 ${retried.task_id}。`); await load(); await readDetail(retried); } catch (error) { setMessage(errorText(error)); } finally { setBusyId(undefined); } };
  const selectCandidateForTask = async (taskId: string, assetId: string, expectedVersion: number) => { setBusyId(taskId); try { await api.selectCandidate(scope.projectId, taskId, assetId, expectedVersion, `xj:${scope.projectId}:candidate:${taskId}:${assetId}`); if (selected?.task.task_id === taskId) await readDetail(selected.task); await load(); setMessage("候选版本已由服务端记录。"); } catch (error) { setMessage(errorText(error)); if (error instanceof GenerationCenterApiError && error.status === 409 && selected?.task.task_id === taskId) await readDetail(selected.task); } finally { setBusyId(undefined); } };
  const selectCandidate = async (assetId: string) => { if (selected) await selectCandidateForTask(selected.task.task_id, assetId, selected.selectedCandidate?.version ?? 0); };
  const submitted = async (task: GenerationTask) => { setMessage(`任务 ${task.task_id} 已由服务端接受，正在读取最终状态。`); await load(); await readDetail(task); };
  if (state === "loading") return <main className="grid min-h-full place-items-center bg-[#110f0d] p-8 text-stone-300" aria-busy="true"><LoaderCircle className="animate-spin text-cyan-200" /><p className="mt-3">正在读取生成任务…</p></main>;
  if (state === "forbidden") return <main className="grid min-h-full place-items-center bg-[#110f0d] p-8"><section role="alert" className="max-w-lg border border-rose-400/30 bg-rose-950/20 p-6 text-rose-100"><h1 className="text-xl font-semibold">无权访问生成任务</h1><p className="mt-2 text-sm leading-6">{message}</p></section></main>;
  if (state === "error") return <main className="grid min-h-full place-items-center bg-[#110f0d] p-8"><section role="alert" className="max-w-lg border border-rose-400/30 bg-rose-950/20 p-6 text-rose-100"><h1 className="text-xl font-semibold">任务读取失败</h1><p className="mt-2 text-sm leading-6">{message}</p><button type="button" onClick={() => void load()} className="mt-4 border border-rose-200/30 px-3 py-2 text-sm">重新读取</button></section></main>;
  return <main className="min-h-full bg-[#110f0d] px-4 py-6 text-stone-100 md:px-7"><div className="mx-auto max-w-[1500px]"><header className="border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex gap-4"><span className="grid size-12 place-items-center border border-cyan-200/30 bg-cyan-200/10 text-cyan-100"><Icon size={23} /></span><div><p className="font-mono text-[11px] tracking-[.18em] text-cyan-200">{config.eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{config.title}</h1><p className="mt-2 text-sm text-stone-400">{scope.projectName ?? scope.projectId} · {config.description}</p></div></div><div className="flex gap-7 text-right"><div><strong className="block text-2xl font-semibold text-amber-100">{processing}</strong><span className="text-xs text-stone-500">处理中</span></div><div><strong className="block text-2xl font-semibold">{total}</strong><span className="text-xs text-stone-500">服务端任务</span></div></div></div></header>
    <div className="mt-5">{message ? <p role="status" className="mb-4 border border-amber-200/20 bg-amber-100/5 p-3 text-sm text-amber-100">{message}</p> : null}<ModelStatus model={model} />{["model-center", "model-detail", "model-market"].includes(view) ? <div className="mt-5"><ModelCatalogPanel model={model} /></div> : null}{view === "model-report" ? <div className="mt-5"><ModelUsagePanel usage={usage} /></div> : null}{view === "video-candidates" ? <div className="mt-5"><CandidateComparison scope={scope} candidates={candidates} total={candidateTotal} selecting={Boolean(busyId)} onSelectCandidate={(taskId, assetId, version) => void selectCandidateForTask(taskId, assetId, version)} /></div> : null}<div className="mt-5"><SubmissionConsole config={config} scope={scope} api={api} onSubmitted={submitted} /></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="border border-white/10 bg-[#171411]/70"><div className="border-b border-white/10 px-5 py-3"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">服务端任务流</h2><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 text-sm text-stone-400 hover:text-stone-100"><RefreshCw size={14} />刷新</button></div><div className="mt-3 grid gap-2 md:grid-cols-3"><select aria-label="按任务状态筛选" value={filters.status ?? ""} onChange={(event) => { setOffset(0); setFilters((current) => ({ ...current, status: (event.target.value || undefined) as GenerationTaskFilters["status"] })); }} className="border border-white/10 bg-black/30 px-2 py-2 text-xs text-stone-200"><option value="">全部状态</option>{Object.entries(taskStatusText).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="按媒体类型筛选" value={filters.mediaType ?? ""} onChange={(event) => { setOffset(0); setFilters((current) => ({ ...current, mediaType: (event.target.value || undefined) as GenerationTaskFilters["mediaType"] })); }} className="border border-white/10 bg-black/30 px-2 py-2 text-xs text-stone-200"><option value="">全部媒体</option><option value="image">图片</option><option value="video">视频</option></select><input aria-label="按能力筛选" value={filters.capability ?? ""} onChange={(event) => { setOffset(0); setFilters((current) => ({ ...current, capability: event.target.value.trim() || undefined })); }} placeholder="能力，例如 video_extend" className="border border-white/10 bg-black/30 px-2 py-2 text-xs text-stone-200" /></div></div>{tasks.length ? <><div>{tasks.map((task) => <TaskRow key={task.task_id} task={task} selected={selected?.task.task_id === task.task_id} busy={busyId === task.task_id} onSelect={() => void readDetail(task)} onCancel={() => void cancel(task)} onRetry={() => void retry(task)} />)}</div><div className="flex items-center justify-between border-t border-white/10 px-5 py-3 text-xs text-stone-400"><span>显示 {offset + 1}–{offset + tasks.length} / {total}</span><div className="flex gap-2"><button type="button" disabled={offset === 0} onClick={() => setOffset((value) => Math.max(0, value - 50))} className="border border-white/10 px-2 py-1 disabled:opacity-40">上一页</button><button type="button" disabled={offset + tasks.length >= total} onClick={() => setOffset((value) => value + 50)} className="border border-white/10 px-2 py-1 disabled:opacity-40">下一页</button></div></div></> : <div className="p-10 text-center"><p className="text-lg text-stone-200">当前筛选条件下没有生成任务</p><p className="mt-2 text-sm text-stone-500">可调整筛选条件，或在 Provider 部署后提交真实任务。</p></div>}</section><DetailPanel detail={selected} onClose={() => setSelected(null)} onSelectCandidate={(assetId) => void selectCandidate(assetId)} selecting={Boolean(busyId)} /></div></div></main>;
}
