"""HTTP gateway for a deployed M07 audio, subtitle, mix or lip-sync provider."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

import httpx

from server.xingjing_audio_persistence.repository import AudioScope


class AudioProviderGatewayError(RuntimeError):
    """A remote media provider did not accept or cancel a task."""


class MediaSubmission:
    """The immutable remote task reference returned after submission."""

    def __init__(self, provider_name: str, provider_task_id: str) -> None:
        self.provider_name = provider_name
        self.provider_task_id = provider_task_id


class HttpAudioMediaProvider:
    """Fail-closed adapter for the configured media Provider gateway.

    The Provider receives trusted scope fields generated by the server, never a
    browser supplied workspace identity.  Completion is returned separately to
    the signed ``/audio-providers/callbacks`` endpoint.
    """

    def __init__(
        self,
        *,
        provider_id: str,
        submit_url: str,
        check_url: str,
        cancel_url_template: str,
        bearer_token: str,
    ) -> None:
        values = (provider_id, submit_url, check_url, cancel_url_template, bearer_token)
        if not all(value.strip() for value in values):
            raise ValueError("AUDIO_PROVIDER_CONFIGURATION_REQUIRED")
        if not submit_url.startswith(("https://", "http://")) or not check_url.startswith(("https://", "http://")):
            raise ValueError("AUDIO_PROVIDER_URL_INVALID")
        if "{job_id}" not in cancel_url_template:
            raise ValueError("AUDIO_PROVIDER_CANCEL_URL_TEMPLATE_INVALID")
        self.provider_id = provider_id.strip()
        self._submit_url = submit_url.strip()
        self._check_url = check_url.strip()
        self._cancel_url_template = cancel_url_template.strip()
        self._bearer_token = bearer_token.strip()

    async def submit(self, *, scope: AudioScope, task: Mapping[str, Any]) -> MediaSubmission:
        task_id = task.get("id")
        if not isinstance(task_id, str) or not task_id:
            raise AudioProviderGatewayError("AUDIO_PROVIDER_TASK_ID_INVALID")
        payload = {
            "taskId": task_id,
            "tenantId": scope.tenant_id,
            "workspaceId": scope.workspace_id,
            "projectId": scope.project_id,
            "taskKind": task.get("task_kind"),
            "resourceType": task.get("resource_type"),
            "resourceId": task.get("resource_id"),
            "maxAttempts": task.get("max_attempts"),
            "providerId": self.provider_id,
        }
        try:
            async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, connect=10.0)) as client:
                response = await client.post(
                    self._submit_url,
                    headers={"Authorization": f"Bearer {self._bearer_token}", "Accept": "application/json"},
                    json=payload,
                )
                response.raise_for_status()
                body = response.json()
        except (httpx.HTTPError, ValueError) as error:
            raise AudioProviderGatewayError("AUDIO_PROVIDER_SUBMISSION_FAILED") from error
        if not isinstance(body, dict):
            raise AudioProviderGatewayError("AUDIO_PROVIDER_INVALID_RESPONSE")
        job_id = body.get("jobId", body.get("job_id"))
        if not isinstance(job_id, str) or not job_id.strip():
            raise AudioProviderGatewayError("AUDIO_PROVIDER_JOB_ID_MISSING")
        name = body.get("providerName", body.get("provider_name", self.provider_id))
        if not isinstance(name, str) or not name.strip():
            raise AudioProviderGatewayError("AUDIO_PROVIDER_NAME_INVALID")
        return MediaSubmission(provider_name=name.strip(), provider_task_id=job_id.strip())

    async def check_lip_sync(self, *, scope: AudioScope, inputs: Mapping[str, Any]) -> Mapping[str, Any]:
        payload = {
            **dict(inputs),
            "tenantId": scope.tenant_id,
            "workspaceId": scope.workspace_id,
            "projectId": scope.project_id,
            "providerId": self.provider_id,
        }
        try:
            async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, connect=10.0)) as client:
                response = await client.post(
                    self._check_url,
                    headers={"Authorization": f"Bearer {self._bearer_token}", "Accept": "application/json"},
                    json=payload,
                )
                response.raise_for_status()
                body = response.json()
        except (httpx.HTTPError, ValueError) as error:
            raise AudioProviderGatewayError("AUDIO_PROVIDER_CHECK_FAILED") from error
        if not isinstance(body, dict) or not isinstance(body.get("allowed"), bool):
            raise AudioProviderGatewayError("AUDIO_PROVIDER_CHECK_INVALID_RESPONSE")
        return body

    async def cancel(self, *, scope: AudioScope, provider_task_id: str) -> None:
        if not provider_task_id.strip():
            raise AudioProviderGatewayError("AUDIO_PROVIDER_TASK_ID_INVALID")
        try:
            async with httpx.AsyncClient(timeout=httpx.Timeout(20.0, connect=10.0)) as client:
                response = await client.post(
                    self._cancel_url_template.format(job_id=provider_task_id),
                    headers={"Authorization": f"Bearer {self._bearer_token}", "Accept": "application/json"},
                    json={
                        "tenantId": scope.tenant_id,
                        "workspaceId": scope.workspace_id,
                        "projectId": scope.project_id,
                    },
                )
                response.raise_for_status()
        except httpx.HTTPError as error:
            raise AudioProviderGatewayError("AUDIO_PROVIDER_CANCELLATION_FAILED") from error
