import { useEffect, useMemo, useState, type FormEvent } from "react";
import { GitFork, LoaderCircle, RefreshCw, Search, ShieldCheck, Store, Workflow } from "lucide-react";
import { createMarketplaceApi, marketplaceError, type ForkRecord, type MarketItem, type TemplateRecord, type TemplateReview } from "./api";

export type MarketplacePageId = "AD-015" | "AD-020" | "AD-049" | "CR-108" | "CR-109" | "CR-110" | "CR-024" | "CR-040" | "CR-041" | "CR-043" | "CR-111" | "CR-112";

const titles: Record<MarketplacePageId, string> = { "AD-015": "导出模板管理", "AD-020": "消息模板", "AD-049": "模板审核", "CR-108": "提交模板审核", "CR-109": "创建模板", "CR-110": "模板详情", "CR-024": "创作者社区", "CR-040": "Fork 授权", "CR-041": "Fork 血缘", "CR-043": "Fork 收益分成", "CR-111": "模板市场", "CR-112": "模板 Fork" };

export function MarketplacePage({ pageId, accessToken }: { pageId: MarketplacePageId; accessToken?: string }) {
  const api = useMemo(() => createMarketplaceApi({ accessToken }), [accessToken]);
  const admin = pageId.startsWith("AD-"); const market = ["CR-024", "CR-040", "CR-041", "CR-043", "CR-111", "CR-112"].includes(pageId);
  return <Shell title={titles[pageId]}>{admin ? <AdminSurface api={api} pageId={pageId} /> : market ? <MarketSurface api={api} pageId={pageId} /> : <TemplateSurface api={api} pageId={pageId} />}</Shell>;
}

function TemplateSurface({ api, pageId }: { api: ReturnType<typeof createMarketplaceApi>; pageId: MarketplacePageId }) {
  const [items, setItems] = useState<TemplateRecord[]>([]); const [selected, setSelected] = useState<TemplateRecord | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setError(null); void api.listTemplates().then(setItems).catch((e: unknown) => setError(marketplaceError(e))).finally(() => setLoading(false)); };
  useEffect(() => {
    void api.listTemplates().then(setItems).catch((e: unknown) => setError(marketplaceError(e))).finally(() => setLoading(false));
  }, [api]);
  const refreshSelected = (item: TemplateRecord) => void api.template(item.id).then(setSelected).catch((e: unknown) => setError(marketplaceError(e)));
  return <div className="grid gap-6 xl:grid-cols-[22rem_minmax(0,1fr)]">{pageId === "CR-109" ? <CreateTemplate api={api} onDone={load} /> : selected && pageId === "CR-110" ? <TemplateDetail item={selected} api={api} onChanged={() => refreshSelected(selected)} /> : <TemplateGuide pageId={pageId} />}<Panel title="工作区模板" loading={loading} error={error} onRetry={load}>{items.length === 0 ? <Empty text="当前工作区暂无模板。" /> : <div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between gap-3"><button type="button" onClick={() => refreshSelected(item)} className="text-left"><h3 className="font-medium text-white">{item.title}</h3><p className="mt-1 text-xs text-slate-400">{item.kind} · v{item.revision} · {item.review_state}</p></button></div><p className="mt-3 text-xs text-slate-500">版本 {item.versions.length} · 审核记录 {item.reviews.length} · {item.tags.join(" / ") || "无标签"}</p>{pageId === "CR-108" && <ReviewSubmission item={item} api={api} onDone={load} onError={setError} />}</article>)}</div>}</Panel></div>;
}

function ReviewSubmission({ item, api, onDone, onError }: { item: TemplateRecord; api: ReturnType<typeof createMarketplaceApi>; onDone: () => void; onError: (message: string) => void }) {
  const [statement, setStatement] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!statement.trim()) return; void api.submitReview(item, statement.trim()).then(() => { setStatement(""); onDone(); }).catch((error: unknown) => onError(marketplaceError(error))); };
  return <form onSubmit={submit} className="mt-4 flex gap-2"><textarea required value={statement} onChange={(event) => setStatement(event.target.value)} placeholder="说明版权、素材来源、示例项目和定价依据" className="min-h-20 min-w-0 flex-1 rounded-lg border border-white/15 bg-slate-950 px-3 py-2 text-xs" /><button className="self-end rounded-lg bg-amber-300 px-3 py-2 text-xs font-bold text-slate-950">提交审核</button></form>;
}

function TemplateDetail({ item, api, onChanged }: { item: TemplateRecord; api: ReturnType<typeof createMarketplaceApi>; onChanged: () => void }) {
  const latest = item.versions.at(-1); const [error, setError] = useState<string | null>(null);
  const createVersion = () => { if (!latest) return; void api.createTemplateVersion(item, { content: latest.content, rights: latest.rights, revenue_shares: latest.revenue_rule.shares, price_minor: latest.price_minor }).then(onChanged).catch((e: unknown) => setError(marketplaceError(e))); };
  return <section className="rounded-2xl border border-amber-300/25 bg-amber-300/[.05] p-5"><h2 className="font-serif text-xl text-white">{item.title}</h2><dl className="mt-4 space-y-2 text-xs text-slate-300"><div className="flex justify-between"><dt>模板 ID</dt><dd className="font-mono">{item.id}</dd></div><div className="flex justify-between"><dt>当前修订</dt><dd>{item.revision}</dd></div><div className="flex justify-between"><dt>发布状态</dt><dd>{item.publication_state}</dd></div><div className="flex justify-between"><dt>审核状态</dt><dd>{item.review_state}</dd></div><div className="flex justify-between"><dt>价格</dt><dd>{latest ? `¥${(latest.price_minor / 100).toFixed(2)}` : "—"}</dd></div></dl><button type="button" disabled={!latest} onClick={createVersion} className="mt-5 w-full rounded-xl bg-amber-300 py-2.5 font-bold text-slate-950 disabled:opacity-40">基于当前内容创建新版本</button>{error && <Error text={error} />}</section>;
}

function CreateTemplate({ api, onDone }: { api: ReturnType<typeof createMarketplaceApi>; onDone: () => void }) {
  const [title, setTitle] = useState(""); const [kind, setKind] = useState("project"); const [sourceId, setSourceId] = useState(""); const [sourceVersion, setSourceVersion] = useState(""); const [tags, setTags] = useState(""); const [scopes, setScopes] = useState("project,assets,storyboard"); const [price, setPrice] = useState("0"); const [authorShare, setAuthorShare] = useState("8000"); const [commercial, setCommercial] = useState(true); const [attribution, setAttribution] = useState(true); const [allowFork, setAllowFork] = useState(true); const [error, setError] = useState<string | null>(null);
  const submit = (event: FormEvent) => { event.preventDefault(); const priceMinor = Number(price); const authorBasisPoints = Number(authorShare); const inherited = scopes.split(",").map((value) => value.trim()).filter(Boolean); if (!title.trim() || !sourceId.trim() || !sourceVersion.trim() || !inherited.length || !Number.isInteger(priceMinor) || priceMinor < 0 || !Number.isInteger(authorBasisPoints) || authorBasisPoints < 0 || authorBasisPoints > 10000) return; void api.createTemplate({ title: title.trim(), kind, content: { schemaVersion: 1, source: { id: sourceId.trim(), versionId: sourceVersion.trim(), kind }, title: title.trim() }, tags: tags.split(",").map((value) => value.trim()).filter(Boolean), price_minor: priceMinor, rights: { scope: "public", commercial_use: commercial, attribution_required: attribution, inheritable_scopes: inherited, allowed_workspace_ids: [], allow_fork: allowFork }, revenue_shares: [{ beneficiary_role: "template_author", basis_points: authorBasisPoints }, { beneficiary_role: "platform", basis_points: 10000 - authorBasisPoints }] }).then(() => { setTitle(""); setSourceId(""); setSourceVersion(""); onDone(); }).catch((e: unknown) => setError(marketplaceError(e))); };
  return <form onSubmit={submit} className="rounded-2xl border border-amber-300/25 bg-amber-300/[.05] p-5"><h2 className="font-serif text-xl text-white">创建正式模板</h2><p className="mt-2 text-sm text-slate-400">绑定真实来源版本；内容、授权、定价与分成共同形成不可变首版本。</p><div className="mt-5 space-y-3"><input value={title} onChange={(e) => setTitle(e.target.value)} required placeholder="模板名称" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" /><select value={kind} onChange={(e) => setKind(e.target.value)} className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5"><option value="project">项目模板</option><option value="storyboard">分镜模板</option><option value="export">导出模板</option><option value="message">消息模板</option></select><input required value={sourceId} onChange={(e) => setSourceId(e.target.value)} placeholder="来源项目/分镜/资产 ID" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" /><input required value={sourceVersion} onChange={(e) => setSourceVersion(e.target.value)} placeholder="不可变来源版本 ID" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" /><input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="标签（逗号分隔）" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" /><input required value={scopes} onChange={(e) => setScopes(e.target.value)} placeholder="可继承范围（逗号分隔）" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" /><input value={price} onChange={(e) => setPrice(e.target.value)} inputMode="numeric" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" placeholder="价格（分）" /><input value={authorShare} onChange={(e) => setAuthorShare(e.target.value)} inputMode="numeric" className="w-full rounded-xl border border-white/15 bg-slate-950 px-3 py-2.5" placeholder="作者分成基点（0-10000）" /><label className="flex gap-2 text-xs"><input type="checkbox" checked={commercial} onChange={(e) => setCommercial(e.target.checked)} />允许商用</label><label className="flex gap-2 text-xs"><input type="checkbox" checked={attribution} onChange={(e) => setAttribution(e.target.checked)} />要求署名</label><label className="flex gap-2 text-xs"><input type="checkbox" checked={allowFork} onChange={(e) => setAllowFork(e.target.checked)} />允许 Fork</label><button className="w-full rounded-xl bg-amber-300 py-2.5 font-bold text-slate-950">创建模板</button>{error && <Error text={error} />}</div></form>;
}

function TemplateGuide({ pageId }: { pageId: MarketplacePageId }) { return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><ShieldCheck className="text-amber-300" /><h2 className="mt-4 font-serif text-xl text-white">{titles[pageId]}</h2><p className="mt-2 text-sm leading-6 text-slate-400">查看真实版本、授权、定价和审核记录；所有变更由服务端版本与幂等控制。</p></section>; }

function MarketSurface({ api, pageId }: { api: ReturnType<typeof createMarketplaceApi>; pageId: MarketplacePageId }) {
  const [items, setItems] = useState<MarketItem[]>([]); const [forks, setForks] = useState<ForkRecord[]>([]); const [query, setQuery] = useState(""); const [cursor, setCursor] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = (next?: string) => { setLoading(true); void api.market(query, next).then((page) => { setItems((old) => next ? [...old, ...page.items] : page.items); setCursor(page.next_cursor); return api.listForks(); }).then(setForks).catch((e: unknown) => setError(marketplaceError(e))).finally(() => setLoading(false)); };
  useEffect(() => {
    void api.market().then((page) => { setItems(page.items); setCursor(page.next_cursor); return api.listForks(); }).then(setForks).catch((e: unknown) => setError(marketplaceError(e))).finally(() => setLoading(false));
  }, [api]);
  const fork = (item: MarketItem) => { const name = window.prompt("请输入新项目名称", `${item.title} - Fork`); if (!name) return; const commercialUse = window.confirm("这个 Fork 项目是否用于商业用途？"); if (commercialUse && !item.rights.commercial_use) { setError("该来源授权不允许商用，无法创建商业 Fork。"); return; } const requested = window.prompt("请输入需要继承的授权范围（逗号分隔）", item.rights.inheritable_scopes.join(",")); if (requested === null) return; const scopes = requested.split(",").map((value) => value.trim()).filter(Boolean); if (!scopes.length || scopes.some((scope) => !item.rights.inheritable_scopes.includes(scope))) { setError("请求的授权范围为空或超出来源许可。"); return; } void api.createFork(item, name, { commercialUse, scopes }).then(() => load()).catch((e: unknown) => setError(marketplaceError(e))); };
  if (pageId === "CR-041") return <ForkLedger forks={forks} />;
  return <Panel title={pageId === "CR-024" ? "社区项目与发布" : "可用模板与项目"} loading={loading} error={error} onRetry={() => load()}>{pageId === "CR-024" && <CommunityPublisher api={api} forks={forks} onPublished={() => load()} onError={setError} />}<form onSubmit={(e) => { e.preventDefault(); load(); }} className="mb-5 flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索标题、标签或 ID" className="min-w-0 flex-1 rounded-xl border border-white/15 bg-slate-950 px-4 py-2.5" /><button className="rounded-xl border border-amber-300/30 px-4 text-amber-200"><Search size={16} /></button></form>{items.length === 0 ? <Empty text="当前筛选下没有已审核发布的内容。" /> : <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex justify-between"><Store className="text-amber-300" /><span className="text-sm text-emerald-300">¥{(item.price_minor / 100).toFixed(2)}</span></div><h3 className="mt-4 font-serif text-xl text-white">{item.title}</h3><p className="mt-2 text-xs text-slate-400">{item.source_kind} · {item.tags.join(" / ") || "无标签"}</p><dl className="mt-4 space-y-2 text-xs text-slate-300"><div className="flex justify-between"><dt>商用</dt><dd>{item.rights.commercial_use ? "允许" : "禁止"}</dd></div><div className="flex justify-between"><dt>署名</dt><dd>{item.rights.attribution_required ? "必须" : "不要求"}</dd></div><div className="flex justify-between"><dt>继承范围</dt><dd>{item.rights.inheritable_scopes.join("、")}</dd></div></dl><button onClick={() => fork(item)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-4 py-2.5 text-sm font-bold text-slate-950"><GitFork size={16} />购买并 Fork</button></article>)}</div>}{cursor && <button disabled={loading} onClick={() => load(cursor)} className="mt-5 rounded-lg border border-white/15 px-4 py-2 text-sm">加载更多</button>}{pageId === "CR-043" && <ForkLedger forks={forks} />}</Panel>;
}

function CommunityPublisher({ api, forks, onPublished, onError }: { api: ReturnType<typeof createMarketplaceApi>; forks: ForkRecord[]; onPublished: () => void; onError: (message: string) => void }) {
  const publish = (fork: ForkRecord) => { const title = window.prompt("请输入社区项目标题"); if (!title) return; void api.forkProject(fork.target_project_id).then((project) => api.publishCommunityProject(fork, project, title)).then(onPublished).catch((e: unknown) => onError(marketplaceError(e))); };
  return <section className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[.04] p-4"><h3 className="text-sm font-semibold text-white">发布我的 Fork 项目</h3>{forks.length === 0 ? <p className="mt-2 text-xs text-slate-400">先从市场购买并 Fork 一个项目，再发布到社区。</p> : <div className="mt-3 flex flex-wrap gap-2">{forks.map((fork) => <button type="button" key={fork.id} onClick={() => publish(fork)} className="rounded-lg border border-amber-300/30 px-3 py-2 text-xs text-amber-100">发布 {fork.target_project_id}</button>)}</div>}</section>;
}

function ForkLedger({ forks }: { forks: ForkRecord[] }) { return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center gap-2"><Workflow className="text-amber-300" /><h2 className="font-serif text-xl text-white">Fork 血缘与授权</h2></div>{forks.length === 0 ? <Empty text="当前工作区还没有 Fork 项目。" /> : <ul className="mt-5 space-y-3">{forks.map((fork) => <li key={fork.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="font-mono text-xs text-amber-200">{fork.id}</p><p className="mt-2 text-sm">真实项目：{fork.target_project_id}</p><p className="mt-1 text-xs text-slate-400">祖先 {fork.ancestor_fork_ids.length} 层 · 授权：{fork.rights_record.granted_scopes.join("、")}</p><p className="mt-1 text-xs text-slate-400">分成：{fork.revenue_rule.shares.map((s) => `${s.beneficiary_role} ${s.basis_points / 100}%`).join(" / ")}</p></li>)}</ul>}</section>; }

function AdminSurface({ api, pageId }: { api: ReturnType<typeof createMarketplaceApi>; pageId: MarketplacePageId }) { const [items, setItems] = useState<TemplateRecord[]>([]); const [error, setError] = useState<string | null>(null); const load = () => void api.adminObjects().then((data) => setItems(data.items)).catch((e: unknown) => setError(marketplaceError(e))); useEffect(() => { void api.adminObjects().then((data) => setItems(data.items)).catch((e: unknown) => setError(marketplaceError(e))); }, [api]); const decide = (template: TemplateRecord, review: TemplateReview, decision: "approve" | "reject") => { const reason = window.prompt("请输入审核理由"); if (!reason) return; void api.adminDecision(template, review, decision, reason).then(load).catch((e: unknown) => setError(marketplaceError(e))); }; const withdraw = (template: TemplateRecord) => { const reason = window.prompt("请输入下架理由"); if (!reason) return; void api.withdrawTemplate(template, reason).then(load).catch((e: unknown) => setError(marketplaceError(e))); }; const kinds = pageId === "AD-015" ? ["export"] : pageId === "AD-020" ? ["message"] : []; const visible = kinds.length ? items.filter((item) => kinds.includes(item.kind)) : items; return <Panel title={pageId === "AD-015" ? "导出模板版本" : pageId === "AD-020" ? "消息模板版本" : "平台模板与审核队列"} error={error} onRetry={load}>{visible.length === 0 ? <Empty text="当前筛选范围没有模板或待审核记录。" /> : <div className="space-y-4">{visible.map((item) => <article key={item.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-white">{item.title}</h3><p className="mt-1 text-xs text-slate-400">{item.kind} · 修订 {item.revision} · {item.review_state} · {item.publication_state}</p></div>{item.publication_state === "published" && <button type="button" onClick={() => withdraw(item)} className="rounded-lg border border-rose-300/40 px-3 py-2 text-xs text-rose-200">下架</button>}</div>{item.reviews.filter((r) => r.status === "pending").map((review) => <div key={review.id} className="mt-3 flex gap-2"><button onClick={() => decide(item, review, "approve")} className="rounded-lg bg-emerald-300 px-3 py-2 text-xs font-bold text-slate-950">审核通过</button><button onClick={() => decide(item, review, "reject")} className="rounded-lg border border-rose-300/40 px-3 py-2 text-xs text-rose-200">驳回</button></div>)}</article>)}</div>}</Panel>; }

function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <main className="min-h-screen bg-[#080d16] px-5 py-8 text-slate-100"><div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-6"><p className="text-xs font-semibold tracking-[.18em] text-amber-200">星镜剧创 · 模板生态</p><h1 className="mt-3 font-serif text-4xl text-white">{title}</h1></header><div className="pt-7">{children}</div></div></main>; }
function Panel({ title, loading, error, onRetry, children }: { title: string; loading?: boolean; error?: string | null; onRetry?: () => void; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex justify-between"><h2 className="font-serif text-xl text-white">{title}</h2>{onRetry && <button onClick={onRetry}><RefreshCw size={16} /></button>}</div>{loading ? <p className="mt-6 flex gap-2 text-sm text-slate-400"><LoaderCircle className="animate-spin" size={16} />读取服务端数据…</p> : children}{error && <Error text={error} />}</section>; }
function Empty({ text }: { text: string }) { return <p className="mt-6 rounded-xl border border-dashed border-white/15 p-5 text-sm text-slate-400">{text}</p>; }
function Error({ text }: { text: string }) { return <p role="alert" className="mt-4 rounded-xl border border-rose-300/30 bg-rose-950/30 p-3 text-sm text-rose-100">{text}</p>; }
