import { useCallback, useEffect, useRef, useState } from "react";
import { ActionError, CreatorPage, StatePanel } from "./shared";
import type { CreatorProjectsPort, ProjectDetail, ProjectSummary } from "./types";

export function ProjectLibraryPage({ api, onNavigate }: { api: CreatorProjectsPort; onNavigate: (target: "create" | "guided-create" | "control", projectId?: string) => void }) {
  const [items, setItems] = useState<ProjectSummary[]>(); const [error, setError] = useState<Error>(); const busy = useRef(new Set<string>());
  const load = useCallback(() => { setError(undefined); api.listProjects({ sort: "updatedAt:desc,id:desc" }).then((r) => setItems(r.items)).catch((e: Error) => setError(e)); }, [api]);
  useEffect(() => { void api.listProjects({ sort: "updatedAt:desc,id:desc" }).then((r) => setItems(r.items)).catch((e: Error) => setError(e)); }, [api]);
  const archive = async (p: ProjectSummary) => { if (busy.current.has(p.id)) return; busy.current.add(p.id); try { await api.projectAction(p.id, p.archived ? "restore" : "archive", {}, p.version); load(); } catch (e) { setError(e as Error); } finally { busy.current.delete(p.id); } };
  return <CreatorPage api={api} permission="project.view" title="项目库">{() => <>{!items && !error && <StatePanel title="正在加载项目…" />}{error && <ActionError error={error} onRetry={load} />}{items?.length === 0 && <StatePanel title="这个工作区还没有项目" detail="创建项目后可继续完善配置、导入剧本并进入生产。" action="新建项目" onAction={() => onNavigate("create")} />}{items && items.length > 0 && <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((p) => <article key={p.id} className="rounded-2xl border border-[#2A2E3A] bg-[#12141B] p-5"><p className="text-xs text-[#7E8494]">{p.type} · {p.targetPlatform}</p><h2 className="mt-1 text-lg font-semibold">{p.name}</h2><p className="mt-2 text-sm text-[#B8BECC]">负责人 {p.ownerName} · {p.productionStatus}</p><div className="mt-4 flex gap-2"><button onClick={() => onNavigate("control", p.id)} className="rounded-lg bg-[#FF6B4A] px-3 py-2">进入总控</button><button aria-label={`${p.archived ? "恢复" : "归档"}${p.name}`} onClick={() => void archive(p)} className="rounded-lg border border-[#2A2E3A] px-3 py-2">{p.archived ? "恢复" : "归档"}</button></div></article>)}</section>}</>}</CreatorPage>;
}

export function ProjectEditorPage({ api, projectId, mode = "quick", onCreated }: { api: CreatorProjectsPort; projectId?: string; mode?: "quick" | "guided"; onCreated?: (id: string) => void }) {
  const [project, setProject] = useState<ProjectDetail>(); const [name, setName] = useState(""); const [error, setError] = useState<Error>(); const [saving, setSaving] = useState(false);
  useEffect(() => { if (projectId) api.getProject(projectId).then((p) => { setProject(p); setName(p.name); }).catch((e: Error) => setError(e)); }, [api, projectId]);
  const save = async () => { setSaving(true); setError(undefined); try { const result = await api.projectAction(projectId ?? "new", projectId ? "update" : "create", { name, mode }, project?.version); setProject(result); onCreated?.(result.id); } catch (e) { setError(e as Error); } finally { setSaving(false); } };
  return <CreatorPage api={api} permission="project.manage" title={projectId ? "编辑项目" : mode === "guided" ? "引导式新建项目" : "快捷新建项目"}>{() => <section className="max-w-2xl rounded-2xl bg-[#12141B] p-6"><label className="block">项目名称<input className="mt-2 w-full rounded-lg border border-[#2A2E3A] bg-[#171922] p-3" value={name} onChange={(e) => setName(e.target.value)} /></label>{error && <ActionError error={error} onRetry={() => void save()} />}<button disabled={!name.trim() || saving} onClick={() => void save()} className="mt-5 rounded-lg bg-[#FF6B4A] px-4 py-2 disabled:opacity-50">{saving ? "保存中…" : "保存项目"}</button>{project && <p className="mt-3 text-sm text-[#22C55E]">已保存 · 版本 {project.version}</p>}</section>}</CreatorPage>;
}

export function ProjectControlPage({ api, projectId, onNavigate }: { api: CreatorProjectsPort; projectId: string; onNavigate?: (target: string) => void }) {
  const [project, setProject] = useState<ProjectDetail>(); const [error, setError] = useState<Error>(); const load = useCallback(() => { void api.getProject(projectId).then(setProject).catch((e: Error) => setError(e)); }, [api, projectId]); useEffect(() => { void api.getProject(projectId).then(setProject).catch((e: Error) => setError(e)); }, [api, projectId]);
  return <CreatorPage api={api} permission="project.view" title="项目总控">{() => <>{error && <ActionError error={error} onRetry={load} />}{!project && !error && <StatePanel title="正在加载项目生产状态…" />}{project && <section className="grid gap-4 lg:grid-cols-3"><article className="rounded-2xl bg-[#12141B] p-5 lg:col-span-3"><h2 className="text-xl font-semibold">{project.name}</h2><p className="mt-2 text-[#B8BECC]">当前阶段：{project.productionStatus} · 版本 {project.version}</p></article>{Object.entries({ "script-import": "剧本导入", "script-checkup": "内容体检", "script-lab": "结构化解析", "ai-director": "AI 导演", "director-assets": "角色场景资产", source: "原文管理", rewrite: "AI 改写", "source-mapping": "原文映射", versions: "版本对比" }).map(([target, label]) => <button key={target} onClick={() => onNavigate?.(target)} className="rounded-xl border border-[#2A2E3A] bg-[#171922] p-4 text-left transition hover:border-[#8B5CF6]"><strong>{label}</strong><span className="mt-1 block text-xs text-[#7E8494]">进入 M03 内容理解工作流</span></button>)}</section>}</>}</CreatorPage>;
}
